services:
  bible_api:
    container_name: bible_api
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
    depends_on:
      bible_postgresql:
        condition: service_healthy
        restart: true
      bible_redis:
        condition: service_healthy
        restart: true
    networks:
      - bible_network

  bible_postgresql:
    container_name: bible_postgresql
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bible_db
    ports:
      - 5432:5432
    volumes:
      - bible_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - bible_network
  bible_redis:
    container_name: bible_redis
    image: redis:latest
    volumes:
      - bible_redis_data:/data
    ports:
      - 6379:6379
    networks:
      - bible_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  bible_postgres_data:
  bible_redis_data:

networks:
  bible_network: